import { z } from 'zod';

const CreateInventoryDtoSchema = z.object({
  stock: z.number(),
});

const CreateReviewDtoSchema = z.object({
  rating: z.number(),
  comment: z.string(),
  userId: z.string(),
});

const CreateDiscountDtoSchema = z.object({
  discount: z.number(),
  expires_at: z.string(),
});

const CreateSpecsSmartphoneDtoSchema = z.object({
  brand: z.string(),
  model: z.string(),
  company: z.string(),
  os: z.string(),
  chipset: z.string(),
  cpu: z.string(),
  gpu: z.string(),
  cardSlot: z.boolean(),
  internal: z.string(),
  dualCamera: z.string(),
  features: z.string(),
  dualVideo: z.string(),
  singleCamera: z.string(),
  singleVideo: z.string(),
  loudspeaker: z.boolean(),
  wlan: z.string(),
  bluetooth: z.string(),
  positioning: z.string(),
  nfc: z.boolean(),
  infraredPort: z.boolean(),
  radio: z.boolean(),
  usb: z.string(),
  batteryType: z.string(),
  charging: z.string(),
  color: z.string(),
  screenType: z.string(),
  screenSize: z.string(),
  resolution: z.string(),
  dimensions: z.string(),
  weight: z.string(),
  build: z.string(),
  sim: z.string(),
});

const CreateSpecsLaptopDtoSchema = z.object({
  brand: z.string(),
  model: z.string(),
  company: z.string(),
  ram: z.string(),
  size: z.string(),
  ssd: z.string(),
  color: z.array(z.string()),
  operatingSystem: z.string(),
  hardDisk: z.string(),
  modelNumber: z.string(),
  processor: z.string(),
  graphicsProcessor: z.string(),
  dedicatedGraphics: z.string(),
  fingerprintSensor: z.string(),
  resolution: z.string(),
  wifiStandardsSupported: z.string(),
  weight: z.string(),
  dimensions: z.string(),
  bluetoothVersion: z.string(),
  numberOfUSBPorts: z.string(),
  series: z.string(),
  internalMic: z.string(),
  touchScreen: z.string(),
  baseClockSpeed: z.string(),
  productName: z.string(),
  touchpad: z.string(),
  batteryCell: z.string(),
  pointerDevice: z.string(),
  cache: z.string(),
  micIn: z.string(),
  speakers: z.string(),
  multiCardSlot: z.string(),
  rj45LAN: z.string(),
  hdmiPort: z.string(),
  ethernet: z.string(),
  batteryLife: z.string(),
  dedicatedGraphicMemoryType: z.string(),
  expandableRAM: z.string(),
});

const CreateSpecsTabletDtoSchema = z.object({
  brand: z.string(),
  model: z.string(),
  launched: z.string().optional(),
  dimensions: z.string(),
  weight: z.string(),
  batteryCapacity: z.string(),
  removableBattery: z.string(),
  color: z.string(),
  screenSize: z.string(),
  touchscreen: z.boolean(),
  resolution: z.string(),
  ppi: z.string(),
  processor: z.string(),
  processorMake: z.string(),
  ram: z.string(),
  internalStorage: z.string(),
  expandableStorage: z.string(),
  rearCamera: z.string(),
  rearFlash: z.string(),
  frontCamera: z.string(),
  operatingSystem: z.string(),
  skin: z.string(),
  wifi: z.string(),
  gps: z.string(),
  bluetooth: z.string(),
  nfc: z.boolean(),
  infrared: z.boolean(),
  usbOtg: z.string(),
  headphones: z.string(),
  fm: z.boolean(),
  wifiDirect: z.boolean(),
  mhl: z.boolean(),
  compassMagnetometer: z.boolean(),
  proximitySensor: z.boolean(),
  accelerometer: z.boolean(),
  ambientLightSensor: z.boolean(),
  gyroscope: z.boolean(),
  barometer: z.boolean(),
  temperatureSensor: z.boolean(),
});

export const CreateProductDtoSchema = z.object({
  name: z.string(),
  price: z.number(),
  category: z.string(),

  inventory: z.array(CreateInventoryDtoSchema),
  reviews: z.array(CreateReviewDtoSchema),
  discounts: z.array(CreateDiscountDtoSchema),
  smartphoneSpecs: CreateSpecsSmartphoneDtoSchema.optional(),
  laptopSpecs: CreateSpecsLaptopDtoSchema.optional(),
  tabletSpecs: CreateSpecsTabletDtoSchema.optional(),
});

export type CreateProductDto = z.infer<typeof CreateProductDtoSchema>;
